export const defaultAnime = [
  {
    id: 'demon-slayer',
    title: 'Demon Slayer: Kimetsu no Yaiba',
    synopsis: 'Tanjiro Kamado, a young boy whose family is slaughtered by a demon, joins the Demon Slayer Corps to find a cure for his sister Nezuko, who has been turned into a demon. Wielding legendary water and fire sword techniques, he fights the upper-rank threats of Muzan Kibutsuji.',
    description: 'Tanjiro Kamado, a young boy whose family is slaughtered by a demon, joins the Demon Slayer Corps to find a cure for his sister Nezuko, who has been turned into a demon. Wielding legendary water and fire sword techniques, he fights the upper-rank threats of Muzan Kibutsuji.',
    banner: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1600&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1600&auto=format&fit=crop&q=80',
    poster: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    genres: ['Action', 'Fantasy', 'Demons'],
    rating: '9.4',
    status: 'Ongoing',
    type: 'Series',
    category: 'Featured',
    featured: true,
    releaseYear: 2019,
    episodeCount: 63,
    totalSeasons: 5,
    studio: 'ufotable',
    malId: 38000,
    createdAt: new Date().toISOString()
  },
  {
    id: 'frieren',
    title: 'Frieren: Beyond Journey\'s End',
    synopsis: 'An elf mage and her former party members reunited after a 10-year quest to defeat the Demon King. As her companions age and pass away, Frieren begins to contemplate the transience of human lives, embarking on a path of self-discovery to understand human hearts.',
    description: 'An elf mage and her former party members reunited after a 10-year quest to defeat the Demon King. As her companions age and pass away, Frieren begins to contemplate the transience of human lives, embarking on a path of self-discovery to understand human hearts.',
    banner: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1600&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1600&auto=format&fit=crop&q=80',
    poster: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=600&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=600&auto=format&fit=crop&q=80',
    genres: ['Adventure', 'Fantasy', 'Drama'],
    rating: '9.6',
    status: 'Ongoing',
    type: 'Series',
    category: 'Trending',
    featured: false,
    releaseYear: 2023,
    episodeCount: 2,
    totalSeasons: 1,
    studio: 'Madhouse',
    malId: 52991,
    createdAt: new Date().toISOString()
  },
  {
    id: 'jujutsu-kaisen',
    title: 'Jujutsu Kaisen',
    synopsis: 'Yuji Itadori, an athletic high school student, accidentally swallows a highly potent cursed finger of the demon Ryomen Sukuna. To save lives and maintain the balance of the Tokyo Jujutsu Shaman College, Yuji submits to Gojo Satoru\'s oversight to collect all fingers.',
    description: 'Yuji Itadori, an athletic high school student, accidentally swallows a highly potent cursed finger of the demon Ryomen Sukuna. To save lives and maintain the balance of the Tokyo Jujutsu Shaman College, Yuji submits to Gojo Satoru\'s oversight to collect all fingers.',
    banner: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=1600&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=1600&auto=format&fit=crop&q=80',
    poster: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600&auto=format&fit=crop&q=80',
    genres: ['Action', 'Mystery', 'Thriller'],
    rating: '9.2',
    status: 'Ongoing',
    type: 'Series',
    category: 'Popular',
    featured: false,
    releaseYear: 2020,
    totalSeasons: 3,
    episodeCount: 6,
    studio: 'MAPPA',
    malId: 40748,
    createdAt: new Date().toISOString()
  },
  {
    id: 'chainsaw-man',
    title: 'Chainsaw Man',
    synopsis: 'Denji is a desperate youth struggling to repay his deceased father\'s astronomical debts to the yakuza by hunting devils. Betrayed and left for dead in a dumpster, he merges with his faithful pochita devil dog, arising as the chainsaw-fused hybrid warrior Chainsaw Man.',
    description: 'Denji is a desperate youth struggling to repay his deceased father\'s astronomical debts to the yakuza by hunting devils. Betrayed and left for dead in a dumpster, he merges with his faithful pochita devil dog, arising as the chainsaw-fused hybrid warrior Chainsaw Man.',
    banner: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=1600&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=1600&auto=format&fit=crop&q=80',
    poster: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=600&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=600&auto=format&fit=crop&q=80',
    genres: ['Action', 'Sci-Fi', 'Fantasy'],
    rating: '8.9',
    status: 'Completed',
    type: 'Series',
    category: 'Regular',
    featured: false,
    releaseYear: 2022,
    episodeCount: 2,
    totalSeasons: 1,
    studio: 'MAPPA',
    malId: 44511,
    createdAt: new Date().toISOString()
  }
];

export const defaultSeasons = [
  { id: 'demon-slayer_1', animeId: 'demon-slayer', number: 1, name: 'Season 1: Unwavering Resolve Arc', title: 'Season 1: Unwavering Resolve Arc', episodeCount: 26, malId: 38000, createdAt: new Date().toISOString() },
  { id: 'demon-slayer_2', animeId: 'demon-slayer', number: 2, name: 'Season 2: Mugen Train Arc (TV)', title: 'Season 2: Mugen Train Arc (TV)', episodeCount: 7, malId: 48316, createdAt: new Date().toISOString() },
  { id: 'demon-slayer_3', animeId: 'demon-slayer', number: 3, name: 'Season 3: Entertainment District Arc', title: 'Season 3: Entertainment District Arc', episodeCount: 11, malId: 47778, createdAt: new Date().toISOString() },
  { id: 'demon-slayer_4', animeId: 'demon-slayer', number: 4, name: 'Season 4: Swordsmith Village Arc', title: 'Season 4: Swordsmith Village Arc', episodeCount: 11, malId: 51019, createdAt: new Date().toISOString() },
  { id: 'demon-slayer_5', animeId: 'demon-slayer', number: 5, name: 'Season 5: Hashira Training Arc', title: 'Season 5: Hashira Training Arc', episodeCount: 8, malId: 55701, createdAt: new Date().toISOString() },
  { id: 'frieren_1', animeId: 'frieren', number: 1, name: 'Season 1: First Journey', title: 'Season 1: First Journey', episodeCount: 28, malId: 52991, createdAt: new Date().toISOString() },
  { id: 'jujutsu-kaisen_1', animeId: 'jujutsu-kaisen', number: 1, name: 'Season 1: Curse Womb Arc', title: 'Season 1: Curse Womb Arc', episodeCount: 24, malId: 40748, createdAt: new Date().toISOString() },
  { id: 'jujutsu-kaisen_2', animeId: 'jujutsu-kaisen', number: 2, name: 'Season 2: Shibuya Incident & Hidden Inventory', title: 'Season 2: Shibuya Incident & Hidden Inventory', episodeCount: 23, malId: 51009, createdAt: new Date().toISOString() },
  { id: 'jujutsu-kaisen_3', animeId: 'jujutsu-kaisen', number: 3, name: 'Season 3: Culling Game Arc', title: 'Season 3: Culling Game Arc', episodeCount: 12, malId: 56894, createdAt: new Date().toISOString() },
  { id: 'chainsaw-man_1', animeId: 'chainsaw-man', number: 1, name: 'Season 1: Public Safety Saga', title: 'Season 1: Public Safety Saga', episodeCount: 12, malId: 44511, createdAt: new Date().toISOString() }
];

export const defaultEpisodes = [
  {
    id: 'demon-slayer_1_1',
    animeId: 'demon-slayer',
    seasonId: 'demon-slayer_1',
    seasonNumber: 1,
    number: 1,
    title: 'Episode 1: Cruelty',
    description: 'Tanjiro Kamado lives a peaceful life selling charcoal in the snowy mountains, until he returns to find his family slaughtered and his sister turned.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    video1080: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    duration: 596,
    createdAt: new Date().toISOString()
  },
  {
    id: 'demon-slayer_1_2',
    animeId: 'demon-slayer',
    seasonId: 'demon-slayer_1',
    seasonNumber: 1,
    number: 2,
    title: 'Episode 2: Trainer Sakonji Urokodaki',
    description: 'Desperate to defend Nezuko, Tanjiro meets Giyu Tomioka who directs him to Mt. Sagiri for rigorous swordplay and breath water training.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    video1080: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1627856013091-fed6e4e30025?w=600&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1627856013091-fed6e4e30025?w=600&auto=format&fit=crop&q=80',
    duration: 653,
    createdAt: new Date().toISOString()
  },
  {
    id: 'frieren_1_1',
    animeId: 'frieren',
    seasonId: 'frieren_1',
    seasonNumber: 1,
    number: 1,
    title: 'Episode 1: The Journey\'s End',
    description: 'The triumph over the Demon King has completed. Frieren bids farewell to her aging human hero comrades to quest for magic, only to return to a tragic parting.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    video1080: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=600&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=600&auto=format&fit=crop&q=80',
    duration: 734,
    createdAt: new Date().toISOString()
  },
  {
    id: 'frieren_1_2',
    animeId: 'frieren',
    seasonId: 'frieren_1',
    seasonNumber: 1,
    number: 2,
    title: 'Episode 2: It Didn\'t Have to Be Magic',
    description: 'Frieren visits her dying wizard companion Heiter and adopts Fern, a young war orphan student with immense potential for mana manipulation.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    video1080: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&auto=format&fit=crop&q=80',
    duration: 150,
    createdAt: new Date().toISOString()
  },
  {
    id: 'jujutsu-kaisen_1_1',
    animeId: 'jujutsu-kaisen',
    seasonId: 'jujutsu-kaisen_1',
    seasonNumber: 1,
    number: 1,
    title: 'Episode 1: Ryomen Sukuna',
    description: 'While attempting to rescue members of his high school occult club, Yuji Itadori swallows a legendary high-grade curse talisman finger.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    video1080: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600&auto=format&fit=crop&q=80',
    duration: 150,
    createdAt: new Date().toISOString()
  },
  {
    id: 'jujutsu-kaisen_1_2',
    animeId: 'jujutsu-kaisen',
    seasonId: 'jujutsu-kaisen_1',
    seasonNumber: 1,
    number: 2,
    title: 'Episode 2: For Myself',
    description: 'Gojo Satoru tests Yuji Itadori\'s will and control over the demon Sukuna before relocating him to the hidden Jujutsu High in Tokyo.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackInTheHills.mp4',
    video1080: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackInTheHills.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    duration: 320,
    createdAt: new Date().toISOString()
  },
  {
    id: 'jujutsu-kaisen_2_1',
    animeId: 'jujutsu-kaisen',
    seasonId: 'jujutsu-kaisen_2',
    seasonNumber: 2,
    number: 1,
    title: 'Episode 1: Hidden Inventory',
    description: 'Go back in time to 2006 as high school prodigies Gojo Satoru and Geto Suguru are assigned a critical escort mission for the Star Religious Group.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    video1080: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    duration: 1420,
    createdAt: new Date().toISOString()
  },
  {
    id: 'jujutsu-kaisen_2_2',
    animeId: 'jujutsu-kaisen',
    seasonId: 'jujutsu-kaisen_2',
    seasonNumber: 2,
    number: 2,
    title: 'Episode 2: Shibuya Incident Begins',
    description: 'On October 31st in Shibuya, a massive veil traps tens of thousands of civilians. Gojo Satoru enters the subterranean station alone.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    video1080: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    duration: 1450,
    createdAt: new Date().toISOString()
  },
  {
    id: 'jujutsu-kaisen_3_1',
    animeId: 'jujutsu-kaisen',
    seasonId: 'jujutsu-kaisen_3',
    seasonNumber: 3,
    number: 1,
    title: 'Episode 1: Executioner',
    description: 'In the aftermath of Shibuya, Yuji Itadori faces immediate execution while the Culling Game Deadly Sorcery Battle Royale is launched across Japan.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    video1080: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    duration: 1420,
    createdAt: new Date().toISOString()
  },
  {
    id: 'jujutsu-kaisen_3_2',
    animeId: 'jujutsu-kaisen',
    seasonId: 'jujutsu-kaisen_3',
    seasonNumber: 3,
    number: 2,
    title: 'Episode 2: Colony Arc',
    description: 'Yuji and Megumi enter the Tokyo Colony No. 1 barrier to track down ancient sorcerers and add rules to protect innocent lives.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
    video1080: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    duration: 1410,
    createdAt: new Date().toISOString()
  },
  {
    id: 'chainsaw-man_1_1',
    animeId: 'chainsaw-man',
    seasonId: 'chainsaw-man_1',
    seasonNumber: 1,
    number: 1,
    title: 'Episode 1: Dog and Chainsaw',
    description: 'Denji hunts rogue local devils under severe yakuza surveillance. When he is butchered, his devil companion Pochita breathes a new life into him.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    video1080: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=600&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=600&auto=format&fit=crop&q=80',
    duration: 155,
    createdAt: new Date().toISOString()
  },
  {
    id: 'chainsaw-man_1_2',
    animeId: 'chainsaw-man',
    seasonId: 'chainsaw-man_1',
    seasonNumber: 1,
    number: 2,
    title: 'Episode 2: Arrival in Tokyo',
    description: 'Denji is recruited by the mysterious Makima to serve in the Public Safety Department as Tokyo\'s experimental live-in rookie devil hunter.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    video1080: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
    duration: 596,
    createdAt: new Date().toISOString()
  }
];
